name: Publish to Test PyPI
on:
    push:
        tags:
          - "[0-9]+.[0-9]+.[0-9]+"
          - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
          - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
          - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+" 
jobs:
    test:
        name: Testing Code on ${{ matrix.os }} with Python ${{ matrix.python-version }} using tox
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            python-version: ["3.11"]
    
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements_dev.txt
        - name: Test with tox
          run: tox
    build: 
      name: Build distribution
      runs-on: macos-latest
      steps:
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.run_id }}
          path: dist/
      - name: Upload distribution artifacts
        run: |
          python -m pip install build
          python -m build

    test-pypi-publish:
        name: Upload release to TestPyPI
        needs: [test, build]
        runs-on: macos-latest
        # Specifying a GitHub environment is optional, but strongly encouraged
        environment: testpypi
        permissions:
          # IMPORTANT: this permission is mandatory for Trusted Publishing
          id-token: write
        steps:
          # retrieve your distributions here
          - name: Download artifacts
            uses: actions/download-artifact@v4
            with:
              name: dist-${{ github.run_id }}
              path: dist/
          
          - name: Publish package distributions to TestPyPI
            uses: pypa/gh-action-pypi-publish@release/v1
